name = "${APP_NAME}"
compatibility_date = "2024-09-16"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[vars]
APP_URL = "${APP_URL}"
COOKIE_SECRET = "${COOKIE_SECRET}"
OIDC_AUTH_SECRET = "${OIDC_AUTH_SECRET}"
OIDC_ISSUER = "${OIDC_ISSUER}"
OIDC_CLIENT_ID = "${OIDC_CLIENT_ID}"
OIDC_CLIENT_SECRET = "${OIDC_CLIENT_SECRET}"
OIDC_REDIRECT_URI = "${OIDC_REDIRECT_URI}"
OIDC_SCOPES = "${OIDC_SCOPES}"

[[d1_databases]]
binding = "DB"
database_name = "${APP_NAME}"
migrations_dir = "src/db/migrations"
database_id = "${CLOUDFLARE_DATABASE_ID}"
